title: "Goから学ぶプログラミング入門 〜型・並行処理・Web開発まで短期でマスター〜"
summary: |
  この書籍は、「まずはGo言語でプログラミングを体験したい」という初心者を想定し、誰でも段階的に理解を深められるように作られています。各章では、文法やデータ構造といった基本から並行処理やWeb/APIの初歩までを解説し、学んだ直後にすぐ使えるサンプルコードと演習課題を提供。さらに、章末のミニテストを使えば、コードを動かせない環境でも紙面で知識の確認が行えます。

  また、本書の最後には、より総合的な巻末テストを用意しているため、「どのレベルまで分かるようになったか」を改めてチェック可能。書籍を一通り読み進めた後で振り返りに使えば、初学者が短期で習得した内容を“再確認”でき、さらなる学習計画も立てやすくなっています。
topics: ["go", "gin"]
published: true
price: 900 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - chapter0
  - chapter1
  - chapter2
  - chapter3
  - chapter4
  - chapter5
  - chapter6
  - chapter7
  - chapter8
  - chapter9
  - quiz
  - quiz_answer